include:
  - local: .gitlab/*.yml

stages:
  - test
  - build
  - release

variables:
  FF_USE_FASTZIP: 'true' # enable fastzip - a faster zip implementation that also supports level configuration.
  ARTIFACT_COMPRESSION_LEVEL: 'fastest' # can also be set to fastest, fast, slow and slowest. If just enabling fastzip is not enough try setting this to fastest or fast.
  CACHE_COMPRESSION_LEVEL: 'fastest' # same as above, but for caches
  TRANSFER_METER_FREQUENCY: 2s # will display transfer progress every 2 seconds for artifacts and remote caches.
  YARN_CACHE_FOLDER: '$CI_PROJECT_DIR/.yarn-cache'

cache:
  key:
    files:
      - yarn.lock
  paths:
    - '.yarn-cache/'
    - '**/node_modules/'
  policy: pull-push

#
#
# === test ===

test-lint-job:
  stage: test
  image: !reference [.pre, image]
  script:
    - !reference [.install, script]
    - yarn lint
